### PR TITLE
Json notification body

### PR DESCRIPTION
**Pull request by mcguirepr89**

### CODE REVIEW

**Comment by ehpersonal38** [comment]
left your lint roller at home? 😆

**Comment by mcguirepr89** [comment]
@ehpersonal38 damn! Thanks for testing! weird

**Comment by mcguirepr89** [comment]
Yep same for me -- shucks -- okay, back to drawing board!

**Comment by ehpersonal38** [comment]
Shucks indeed! You know you're getting into the weeds when you start dealing with the intricacies of quotes and how to escape them properly. I still am so lost on all that.

Maybe just have a single variable for the title and body $json that dumps all the parameters in a nice json format?

**Pull request closed without merging**
