### PR TITLE
adding a new daily_plot.py for review

### PR DESCRIPTION
**Pull request by CaiusX**
Now you put whatever notes you might have here

Assign me as a reviewer and an assignee if there is something I need to do with the request 

Give it a label and then you just click create the pull request

### CODE REVIEW

**Review by mcguirepr89 — CHANGES_REQUESTED** [review]
We'll wait till `configparser`

**Comment by CaiusX** [comment]
Not sure if this all worked on the github side - latest file has been "pushed",

I didn't use configparser ultimately, rather read thisrun.txt & extracted the DB_PWD from that.

Please test.

**Comment by mcguirepr89** [comment]
Awesome, thank you., buddy! I'll give it a test today. I'm hoping to work on documentation today, so if you don't get any feedback from me today on this, you should get some tomorrow.

**Review by mcguirepr89 — COMMENTED** [review]
Looks great and works great! Thanks, Dennis!

**Comment by mcguirepr89** [comment]
Would you be able to do this also for `server.py` so that we can get the password out of the code??

**Comment by CaiusX** [comment]
Cool, which "branch" is server.py on?

**Comment by mcguirepr89** [comment]
It is in `forms` now

**Pull request merged**
