### PR TITLE
Update todays_detections.php

### PR DESCRIPTION
**Pull request by ehpersonal38**
Two main changes:
1) A "Show 40 more detections" button has been added, which helps limit the number of detections shown at once, significantly improving performance when you have a lot of detections in one day.
2) Because of this performance increase, a spectrogram image with accompanying audio can be displayed, like the one on the "Overview" page. This makes it a little more intuitive to listen to the recordings.

### CODE REVIEW

**Review by mcguirepr89 — COMMENTED** [review]
This is awesome! I'm going to test it out and then will likely accept this -- THANK YOU!

**Comment by ehpersonal38** [comment]
> This is awesome! I'm going to test it out and then will likely accept this -- THANK YOU!

You're very welcome! Happy to be able to contribute :)

**Comment by ehpersonal38** [comment]
@mcguirepr89 Okay so I had some time to mess around and I (of course) went and tried implementing javascript into this. I haven't tested it thoroughly but try it out and let me know what you think! The main advantages are that it removes the page refresh which looks nicer, and only loads the data we need (i.e. db rows 40-80, then 80-120) and appends it to the page, using less data and less stress on the DB.

(not sure the best way to get this to you - don't want to do a pull request yet, but rename this to .php)
[todays_detections.txt](https://github.com/mcguirepr89/BirdNET-Pi/files/8497886/todays_detections.txt)

**Comment by mcguirepr89** [comment]
I like it and agree it's way cooler to not reload the page -- definitely do a PR for it so you can get you name on that code!

**Pull request merged**
