### PR TITLE
use "localhost" like all other internal services do

### PR DESCRIPTION
**Pull request by Nachtzuster**

### CODE REVIEW

**Comment by mcguirepr89** [comment]
Just curious, does this fix something?

**Comment by Nachtzuster** [comment]
It is more like changing an 'improper' address to the standard one
Using 'localhost' is the proper 'address' for internal messaging https://docs.python.org/3/howto/sockets.html#ipc 
127.0.1.1 (I had to google this) is kind of a placeholder address to satisfy DNS needs of some quirky software if the machine does not have a real address. https://askubuntu.com/questions/754213/what-is-difference-between-localhost-address-127-0-0-1-and-127-0-1-1

**Comment by mcguirepr89** [comment]
So long as it goes to the loopback interface, I'm happy!

**Comment by srchild** [comment]
I just updated my installation and the log showed repeated Errno 111 connection refused in analyze.py

I reverted anaylze.py to 127.0.1.1 instead of localhost and it started working again

**Comment by ehpersonal38** [comment]
Did you try restarting all services? I had this error for a minute too, but I restarted services during something else I was working on and now all seems well

**Comment by ehpersonal38** [comment]
@mcguirepr89 Any issue with adding a `bash restart_services.sh` to the end of update_birdnet_snippets.sh?

**Comment by mcguirepr89** [comment]
@ehpersonal38 I have no issue with that :)

**Comment by srchild** [comment]
Apologies, I went offline for a while after posting this, and also shutdown my Pi to resite it.

When I started up again I found another update had been posted, so I installed that and all is well now :)

**Pull request merged**
