### PR TITLE
Fix/midnightbug

### PR DESCRIPTION
**Pull request by Nachtzuster**
This re-enables deletion of old capture and analyzed directories.
This time it is deleting not yesterday's directory, but the one from 2 days ago.

### CODE REVIEW

**Comment by CaiusX** [comment]
Hi @Nachtzuster 

Thanks for this - if you are comfortable/other users are happy we can merge into the main branch.

**Comment by ehpersonal38** [comment]
Hmm I'm afraid I don't know enough about bash to understand how this works - would be great if Patrick would chime in but I know he's on break

> Hi @Nachtzuster
> 
> Thanks for this - if you are comfortable/other users are happy we can merge into the main branch.

I'm not sure how this fixes things (don't know enough about the midnight bug), but I can't see how it would break anything, so it has my vote.

**Comment by CaiusX** [comment]
Hi @ehpersonal38 & @Nachtzuster 

I managed to screw this up, I merging the Fix to main without testing.  Have been trying (unsuccessfully to far to revert) - please could either of you help out to get main working!!

Thanks
AP

**Comment by CaiusX** [comment]
OK, did a clean re-install and system seems to work fine.

The extract_new_birdsounds.sh looks weird though - Lines 29-35 #Removes old directories seems to be commented out!!

Wish someone with better Git and Bash experience could test and get this into the main - both my systems caught the midnight bug last night!!

**Comment by ehpersonal38** [comment]
> The extract_new_birdsounds.sh looks weird though - Lines 29-35 #Removes old directories seems to be commented out!!

Actually I think that's how they're supposed to be. I went to an older branch and looked at the code and they're commented out as well.

So this PR resulted in errors?

**Comment by CaiusX** [comment]
Yeah, but may have been because I didn’t stash some files, my privacy_server.py seemed to bomb. 
How do I pull and test a branch on my test system, whilst being able to revert to the old main if it bombs? I find this whole git thing incredibly confusing.

**Comment by ehpersonal38** [comment]
> Yeah, but may have been because I didn’t stash some files, my privacy_server.py seemed to bomb. How do I pull and test a branch on my test system, whilst being able to revert to the old main if it bombs? I find this whole git thing incredibly confusing.

Not sure the "right" way to do it, but I would just copy and paste the .sh file onto my machine and try it first.

**Comment by Nachtzuster** [comment]
Just checking in here..
I did test this branch before doing the PR, so i hope the issues seen here are just due to git confusing people.
Let me know if you do suspect issues with the patch

**Pull request merged**
