### PR TITLE
Notifications

### PR DESCRIPTION
**Pull request by mcguirepr89**
Starting the PR to work out the kinks and probably ditch the Pushed.co section altogether since it's a bit redundant now

### CODE REVIEW

**Comment by mcguirepr89** [comment]
I'm going to remove the section in `config.php` that is dedicated to Pushed.co and will make that section just about apprise notifications.

I'll also be thinking about a few tweaks to the species notifier -- it currently is the "bug" in "TinyFileManager" preventing 100% using the web interface to create and restore backups. (I'm sure it's just going to be a flag for sqlite3 that won't create the database if it doesn't exist -- that is the "bug" that creates a database before a backup can be restored -- totally dumb)

**Comment by ehpersonal38** [comment]
I ran into that issue yesterday!

**Comment by mcguirepr89** [comment]
Okie doakie -- pretty close here -- just need to run `restart_services.sh` whenever the "Notify each new detection" checkbox changes state! Ideas?

**Comment by ehpersonal38** [comment]
> Okie doakie -- pretty close here -- just need to run `restart_services.sh` whenever the "Notify each new detection" checkbox changes state! Ideas?

Yes I can get that made up real quick! I'm interested in why they need to be restarted though?

**Comment by ehpersonal38** [comment]
^^ haven't tested that butttttttt it should work, or at least be of use 🤞

**Comment by mcguirepr89** [comment]
>Yes I can get that made up real quick! I'm interested in why they need to be restarted though?

Awesome!
The service needs to be restarted because it is run like this:
1. `sudo systemctl start birdnet_server.service`
1. `birdnet_server.service` calls whatever binary or script it finds configured as its `ExecStart`
1. The script it finds is `server.py`, so that gets started as a process
1. `birdnet_server.service` only starts once (per boot and unless specifically restarted). It builds the model, loads the `labels.txt` file and then waits for metadata from the `birnet_analysis.service`.

Since, as you can see, it only starts up once per boot, if anything about its operation needs to change, you have to restart the service. If you don't restart the service, the script never gets rerun and changes never take effect.

I hope that's not overly explainitory while also missing the point? let me know?

**Comment by mcguirepr89** [comment]
>^^ haven't tested that butttttttt it should work, or at least be of use crossed_fingers

Looks good to me -- I'll "check" it "out" hehe

**Comment by mcguirepr89** [comment]
Ugh ok I'm not going to test it because then I have to sign up for some notification service!!! Is there a really really really simple one I can use just for testing that you know of?

**Comment by ehpersonal38** [comment]
> > Yes I can get that made up real quick! I'm interested in why they need to be restarted though?
> 
> Awesome! The service needs to be restarted because it is run like this:
> 
> 1. `sudo systemctl start birdnet_server.service`
> 2. `birdnet_server.service` calls whatever binary or script it finds configured as its `ExecStart`
> 3. The script it finds is `server.py`, so that gets started as a process
> 4. `birdnet_server.service` only starts once (per boot and unless specifically restarted). It builds the model, loads the `labels.txt` file and then waits for metadata from the `birnet_analysis.service`.
> 
> Since, as you can see, it only starts up once per boot, if anything about its operation needs to change, you have to restart the service. If you don't restart the service, the script never gets rerun and changes never take effect.
> 
> I hope that's not overly explainitory while also missing the point? let me know?

I think I understand - but in server.py I did write it so that every detection, it rechecks birdnet-conf for the latest apprise values. (not that that's very efficient, but it works for now). So wouldn't that negate the need to restart server.py to recheck the conf?

**Comment by mcguirepr89** [comment]
>I think I understand - but in server.py I did write it so that every detection, it rechecks birdnet-conf for the latest apprise values. (not that that's very efficient, but it works for now). So wouldn't that negate the need to restart server.py to recheck the conf?

It would!!!! But is still worth testing -- -- I have a doctors appointment now until 8, then I have dinner, so I'll probably get back to this tomorrow, but great touch and sorry to have overlooked that thoughtful way of adding code :)

**Comment by mcguirepr89** [comment]
Tested before my appointment and it was great -- I'lll merge this (or you can) whenever the chance presents itself

Thank you for you for all of your awesome work!

**Comment by ehpersonal38** [comment]
> > I think I understand - but in server.py I did write it so that every detection, it rechecks birdnet-conf for the latest apprise values. (not that that's very efficient, but it works for now). So wouldn't that negate the need to restart server.py to recheck the conf?
> 
> It would!!!! But is still worth testing -- -- I have a doctors appointment now until 8, then I have dinner, so I'll probably get back to this tomorrow, but great touch and sorry to have overlooked that thoughtful way of adding code :)

No worries! Have a good appointment and dinner!

**Pull request merged**
