### PR TITLE
Fixed year number

### PR DESCRIPTION
**Pull request by gerritzen**
Only one character, should be self-explanatory :)

### CODE REVIEW

**Comment by lloydbayley** [comment]
Pretty sure that's the date of the model, so it would stand.

**Comment by gerritzen** [comment]
Yeah, but the 2.3 model was released in 2023. Am 04.05.2023 um 12:08 schrieb lloydbayley ***@***.***>:﻿
Pretty sure that's the date of the model, so it would stand.

**Comment by lloydbayley** [comment]
Pretty sure I was using it before xmas but I could be mistaken. Will bow of out this and let @ehpersonal38 give a definitive answer.

**Comment by ehpersonal38** [comment]
The 2.3 model update was just last week I think, indeed 2023. Merging now, thanks.

**Comment by lloydbayley** [comment]
Wrong again....sigh

**Comment by ehpersonal38** [comment]
We're all wrong about hundreds of things per day, Lloyd. Thank goodness we're not robots who are always right. Oh wait, even ChatGPT is wrong a lot of the time!

**Pull request merged**
