### PR TITLE
Tidy up some UI things that were bugging me.

### PR DESCRIPTION
**Pull request by lloydbayley**
These are only cosmetic changes to make things a little-more streamlined in the **Settings** area.
If you don't like them, I won't be offended! (Much). :)
Most of the changes are in the Advanced page to make it look more like the basic (config.php) page.

An example:

image

### CODE REVIEW

**Comment by lloydbayley** [comment]
Ultimately, I'd like to tidy up the indenting to make things easier to edit but it's a HUGE job so I'll put that on the backburner for a while! :)

**Comment by ehpersonal38** [comment]
Thank you Lloyd! Looks much better. Also don't mind the reverts, just had a mini heart attack after seeing some fatal errors from Git. Turned out just to be my installation, and had to `rm -rf .git` and reinitialize it 😄

**Comment by lloydbayley** [comment]
And I also had a mild one upon seeing this! :)

image

**Comment by lloydbayley** [comment]
Dear ME, I missed a few things in the advanced.php. I"ll save them up because two things isn't enough for a PR. :)

**Pull request merged**
