### PR TITLE
Updated daily_plot.py file, reading from MariaDB

### PR DESCRIPTION
**Pull request by CaiusX**
1. Reads daily data from MariaDB rather than BirdDB.txt
2. Includes boxenplot of confidence for Top-10 species

Patrick - this is my first attempt at a Github upload, so tell me if I'm doing it right?  Also check that the script works on your system before including in Main pls!

### CODE REVIEW

**Comment by mcguirepr89** [comment]
Thanks @CaiusX!!!! I'll check it out and will let you know! Awesome!

**Comment by mcguirepr89** [comment]
I do spot a DB password in there -- is that something that will need to get replaced during installation/updates the way the DB password is updated in `analyze.py`? Also, I can see that you're utilizing port 3306 to access the DB -- is that required? The default installation only listens on the socket and not port 3306 -- I can probably open this up by default without too much issue, but I want to fully understand the requirements here before making any of those types of changes.

**Comment by mcguirepr89** [comment]
I'm going to close this pull request -- go ahead and make your new branch from `forms` -- I won't want to merge into `main` before testing and making sure things work with `forms`

To make your changes on a branch that uses `forms` as its base:
1. Be sure you're on the `forms` branch
    ```
    cd ~/BirdNET-Pi && git checkout forms
    ```
1. Then create your new branch from that
    ```
    git checkout -b new_daily_plot
    ```
1. Then, after you've made your changes, you can create a pull request and ensure that the pull request is into the `forms` branch.

Thank you!!!!!!!!!!!!!!!!!!!

PS I can put together a little set of steps to handle `git` in the command line a bit more if you're interested? Just let me know if you think that would help with your workflow.

My best

**Comment by CaiusX** [comment]
Hi @mcguirepr89 

Cool, I'll look at it tomorrow if work remains quiet!  

I need to get my head around system variables & how to get them into python so that we can read the passwords from that rather than exposing them in the script.  Will probly need your advice on this - how do I list the available system variables?

I'll do some reading around the need for Port 3306 - I suspect it's required for SQLAlchemy on remote systems.

Best

**Comment by CaiusX** [comment]
Hi @mcguirepr89 

Still getting my head around this github pull/commit process - will take you up on your offer of GIT command line tricks.

The updated daily_plot.py file is working on my main system (JHB-ZA) without using SQLAlchemy and opening ports - you can nomachine in and grab it from the scripts folder.  The password is still exposed tho...

Somehow I've managed to break the automatic running of the daily_plot.py file (every 3 minutes).  Running daily_plot.py manually updates to the correct directory.  I cant for the life of me find which script does this!

Best 
AP

**Pull request closed without merging**
