### PR TITLE
Code Consolidation for API preparations & hard coded path replacements

### PR DESCRIPTION
**Pull request by jaredb7**
Review required!!
This is my attempt at consolidating code and functionality into a common file to later be also used by a API.

No functionality has changed, just the code has moved and a bunch of helper functions written to make life easier (saveSettings(), getDirectory() and getFilePath() are some of them)
Everywhere some functionality existed that was moved into a function in common.php I've tested those pages and any actions (like protecting recordings) etc.

- All SQL Queries were moved into their respective functions and parameterised, there were some slight logic changes in the front end pages to accommodate data being returned differently but actual data returned and functionality is maintained

- A common function is used to execute all queries and looks after binding any parameterised values that have been supplied. We're already using prepared statement so updated all queries that would accept input from the user with place-holders which are later bound into the statement.

- The Config and Advanced setting pages received changes to use the new setSetting() function which looks after creating or updating the setting in the required config files. It also refreshed the global $config variable by re-reading the config files after saving. Optionally it also specification of a command to run after saving the settings.

- Service Controls page received changes with the replacement of the actual command to execute with a sort of shorthand human friendly versions e.g. service <action> <service_name> -- service restart livestream.service.
These commands map to the original commands in serviceMaintenance() so this could be called through the API without needing the full-blown commend.
views.php was updated to accommodate this also

- System Controls page received a small change to make the process checking for new git updates or getting the last commit hash a single function call

- Two new functions getDirectory() and getFilePath() were introduced in aims and make it easier to relocate files in the future. This has been worked into all existing php files to replace all hard coded paths.
Currently the home directory is still fixed to that of user id 1000 (normally pi) but can be changed once we get around to needed that.

- Other misc code for deleting / protecting detection's, frequency shift, Flickr API call etc have also been moved into common.php to be used later by the API as well

- Excuse the misleading branch name 😄

### CODE REVIEW

**Comment by jaredb7** [comment]
Hi @Svardsten53 , I did see your modified version, I like the weather at in the title :)

Correct all existing pages will call common.php to execute code that was in that file but now moved into common.

The layout/html code out from index.php, views.php etc to build the appearance we see today won't change or be replaced. So your script used to do the translations will continue to work after any tweaks if necessary, 
I assume you're just finding and replacing the English text with Swedish?

The idea was we keep the current look and feel and output untouched, moved any code that can be reused to common.php, build a API that reuses that same code, then a new web interface can build off the data from the API.

**Comment by ehpersonal38** [comment]
This is an absolute monolith of code, I'm honestly shocked but a bit scared 😄 

Anyways, there's a fatal error showing on my system when I tested this PR out - 
chrome_yoQw8EKPrS

**Comment by jaredb7** [comment]
It is quite a large change lol, hopefully the PHP comments made it a little less freighting haha 😅

Whoops and apologies, I'll investigate the error, I think it may be because it can't find the new config directory with the new json file which I've probably linked onto /homepage on my install but haven't added it into update_snippets

**Comment by jaredb7** [comment]
It was the missing symlink :(

`[ -L ~/BirdSongs/Extracted/config ] || ln -sf ~/BirdNET-Pi/config ~/BirdSongs/Extracted`

I committed the change to the same branch and opened a new PR, I'm sure there some magic you're able to do to revert the revert & pull in the fix :)

**Comment by ehpersonal38** [comment]
Are you able to re-open this PR by chance?

**Comment by ehpersonal38** [comment]
> Would it be beneficial in creating a new PR, with the fix from https://github.com/mcguirepr89/BirdNET-Pi/pull/919 and resolve any conflicts then submit it against PR-Development and see how that looks?

Yep, let's try that!

**Comment by jaredb7** [comment]
New PR #925 submitted against the PR Dev branch, I pulled in the latest commits to the main branch, made adjustments and resolved the conflicts that were occurring.
This also has #919 in it some small changes

Then I compared the files again what I have been running for the past few weeks just to see what I may have to re-test and there were no odd changes after resolving things.

I tested the new frequency shift option on the spectrogram page and also the 30Day graphs fix and fixed the issue my code created (wasn't supplying valid data)

**Pull request merged**
