### PR TITLE
Daily new species notifier

### PR DESCRIPTION
**Pull request by mcguirepr89**
Linted -- still testing -- it would be really cool to add the JSON body option for the notifications before merging this, so I'll likely take my time getting that working here as well

### CODE REVIEW

**Comment by mcguirepr89** [comment]
Would anyone be able to test this out?

```
update_birdnet.sh -b daily_new_species_notifier
```

and let me know how that works for you?

**Comment by ehpersonal38** [comment]
@mcguirepr89 Just need this output or do you need any more tests done?
```
pi@birdnetpi:~/BirdNET-Pi$ update_birdnet.sh -b daily_new_species_notifier
+ sudo -u pi git -C /home/pi/BirdNET-Pi reset --hard
HEAD is now at c19e4b5 Update config.php
+ set +x
+ sudo -u pi git -C /home/pi/BirdNET-Pi fetch origin daily_new_species_notifier
remote: Enumerating objects: 27, done.
remote: Counting objects: 100% (27/27), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 27 (delta 17), reused 27 (delta 17), pack-reused 0
Unpacking objects: 100% (27/27), 5.62 KiB | 151.00 KiB/s, done.
From https://github.com/mcguirepr89/BirdNET-Pi
 * branch            daily_new_species_notifier -> FETCH_HEAD
   fe19a6d..e19e22f  daily_new_species_notifier -> origin/daily_new_species_notifier
+ set +x
+ sudo -u pi git -C /home/pi/BirdNET-Pi switch -C daily_new_species_notifier --track origin/daily_new_species_notifier
Branch 'daily_new_species_notifier' set up to track remote branch 'daily_new_species_notifier' from 'origin'.
Switched to a new branch 'daily_new_species_notifier'
+ set +x
WARNING: The directory '/home/pi/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
WARNING: Ignoring invalid distribution -pprise (/home/pi/BirdNET-Pi/birdnet/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -pprise (/home/pi/BirdNET-Pi/birdnet/lib/python3.9/site-packages)
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: pip in ./birdnet/lib/python3.9/site-packages (22.1)
Collecting pip
  Downloading https://www.piwheels.org/simple/pip/pip-22.1.2-py3-none-any.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 1.2 MB/s eta 0:00:00
WARNING: Ignoring invalid distribution -pprise (/home/pi/BirdNET-Pi/birdnet/lib/python3.9/site-packages)
Installing collected packages: pip
  Attempting uninstall: pip
    WARNING: Ignoring invalid distribution -pprise (/home/pi/BirdNET-Pi/birdnet/lib/python3.9/site-packages)
    Found existing installation: pip 22.1
    Uninstalling pip-22.1:
      Successfully uninstalled pip-22.1
WARNING: Ignoring invalid distribution -pprise (/home/pi/BirdNET-Pi/birdnet/lib/python3.9/site-packages)
Successfully installed pip-22.1.2
WARNING: Ignoring invalid distribution -pprise (/home/pi/BirdNET-Pi/birdnet/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -pprise (/home/pi/BirdNET-Pi/birdnet/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -pprise (/home/pi/BirdNET-Pi/birdnet/lib/python3.9/site-packages)
WARNING: The directory '/home/pi/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
WARNING: Ignoring invalid distribution -pprise (/home/pi/BirdNET-Pi/birdnet/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -pprise (/home/pi/BirdNET-Pi/birdnet/lib/python3.9/site-packages)
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pytest==7.1.2
  Downloading https://www.piwheels.org/simple/pytest/pytest-7.1.2-py3-none-any.whl (297 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 297.0/297.0 kB 643.6 kB/s eta 0:00:00
Collecting pytest-mock==3.7.0
  Downloading https://www.piwheels.org/simple/pytest-mock/pytest_mock-3.7.0-py3-none-any.whl (12 kB)
Collecting py>=1.8.2
  Downloading https://www.piwheels.org/simple/py/py-1.11.0-py2.py3-none-any.whl (98 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.7/98.7 kB 727.3 kB/s eta 0:00:00
Collecting iniconfig
  Downloading https://www.piwheels.org/simple/iniconfig/iniconfig-1.1.1-py2.py3-none-any.whl (5.0 kB)
Requirement already satisfied: packaging in ./birdnet/lib/python3.9/site-packages (from pytest==7.1.2) (21.3)
Collecting tomli>=1.0.0
  Downloading https://www.piwheels.org/simple/tomli/tomli-2.0.1-py3-none-any.whl (12 kB)
Collecting pluggy<2.0,>=0.12
  Downloading https://www.piwheels.org/simple/pluggy/pluggy-1.0.0-py2.py3-none-any.whl (13 kB)
Requirement already satisfied: attrs>=19.2.0 in ./birdnet/lib/python3.9/site-packages (from pytest==7.1.2) (21.4.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in ./birdnet/lib/python3.9/site-packages (from packaging->pytest==7.1.2) (3.0.8)
WARNING: Ignoring invalid distribution -pprise (/home/pi/BirdNET-Pi/birdnet/lib/python3.9/site-packages)
Installing collected packages: iniconfig, tomli, py, pluggy, pytest, pytest-mock
WARNING: Ignoring invalid distribution -pprise (/home/pi/BirdNET-Pi/birdnet/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -pprise (/home/pi/BirdNET-Pi/birdnet/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -pprise (/home/pi/BirdNET-Pi/birdnet/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -pprise (/home/pi/BirdNET-Pi/birdnet/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -pprise (/home/pi/BirdNET-Pi/birdnet/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -pprise (/home/pi/BirdNET-Pi/birdnet/lib/python3.9/site-packages)
Successfully installed iniconfig-1.1.1 pluggy-1.0.0 py-1.11.0 pytest-7.1.2 pytest-mock-3.7.0 tomli-2.0.1
WARNING: Ignoring invalid distribution -pprise (/home/pi/BirdNET-Pi/birdnet/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -pprise (/home/pi/BirdNET-Pi/birdnet/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -pprise (/home/pi/BirdNET-Pi/birdnet/lib/python3.9/site-packages)
+ my_dir=/home/pi/BirdNET-Pi/scripts
+ sudo systemctl stop birdnet_server.service
+ sudo systemctl stop birdnet_recording.service
+ services=(icecast2.service extraction.service birdnet_recording.service birdnet_log.service)
+ for i in "${services[@]}"
+ sudo systemctl restart icecast2.service
+ for i in "${services[@]}"
+ sudo systemctl restart extraction.service
+ for i in "${services[@]}"
+ sudo systemctl restart birdnet_recording.service
+ for i in "${services[@]}"
+ sudo systemctl restart birdnet_log.service
+ sudo systemctl start birdnet_server.service
+ sleep 5
+ for i in {1..5}
+ systemctl is-active --quiet birdnet_server.service
+ grep 5050 /dev/fd/63
++ netstat -tulpn
tcp        0      0 127.0.0.1:5050          0.0.0.0:*               LISTEN      3962985/python3
+ logger '[/usr/local/bin/restart_services.sh] birdnet_server.service is running'
+ break
+ systemctl is-active --quiet birdnet_server.service
+ grep 5050 /dev/fd/63
++ netstat -tulpn
tcp        0      0 127.0.0.1:5050          0.0.0.0:*               LISTEN      3962985/python3
+ status=0
+ ((  status != 0  ))
+ sudo systemctl restart birdnet_analysis.service
```

**Comment by mcguirepr89** [comment]
If you don't mind also testing some notifications with these two different notification bodies, that would be the other test and if you can ensure the detections are written to the database, that ought to check all my boxes

JSON
```
{"latitude": $latitude, "confidence": $confidence, "longitude": $longitude, "date": $date, "time": $time, "week": $week, "overlap": $overlap, "sens": $sens, "cutoff": $cutoff}
```

and normal
```
$latitude $comname $overlap $cutoff $week $time $date $sens $listenurl $sciname
```

Thanks, @ehpersonal38!!!!

**Comment by ehpersonal38** [comment]
Looks good!
Discord_18XF6lRhYx

**Comment by mcguirepr89** [comment]
Hi, @joeweiss -- I'm about to merge this into main soon, but meant to ask you what the workflow is for the scripts in the new `tests` directory? The update will install pytest now, but I'm not sure where it is in use? I also am unable to call the `tests/test_apprise_notifications.py` file using `~/BirdNET-Pi/birdnet/bin/python3 ~/BirdNET-Pi/tests/test_apprise_notifications.py` --- this is the traceback:
```
Traceback (most recent call last):
  File "/home/birdie/BirdNET-Pi/tests/test_apprise_notifications.py", line 4, in <module>
    from scripts.utils.notifications import sendAppriseNotifications
ModuleNotFoundError: No module named 'scripts'
```

It seems the relative import can't find the utils since it needs to reach the parent directory before going to `scripts.utils.`, I think??

**Comment by mcguirepr89** [comment]
Thank you, @ehpersonal38!!

**Comment by joeweiss** [comment]
> Hi, @joeweiss -- I'm about to merge this into main soon, but meant to ask you what the workflow is for the scripts in the new `tests` directory? The update will install pytest now, but I'm not sure where it is in use? I also am unable to call the `tests/test_apprise_notifications.py` file using `~/BirdNET-Pi/birdnet/bin/python3 ~/BirdNET-Pi/tests/test_apprise_notifications.py` --- this is the traceback:
> 
> ```
> Traceback (most recent call last):
>   File "/home/birdie/BirdNET-Pi/tests/test_apprise_notifications.py", line 4, in <module>
>     from scripts.utils.notifications import sendAppriseNotifications
> ModuleNotFoundError: No module named 'scripts'
> ```
> 
> It seems the relative import can't find the utils since it needs to reach the parent directory before going to `scripts.utils.`, I think??

Running `pytest -s` from the `BirdNET-Pi` directory will run the tests. pytest will find the tests cases from the `test` directory.

```
cd BirdNET-Pi
source birdnet/bin/activate
pytest -s
```

It looks like the tests are currently failing due to the new positional arguments added to `sendAppriseNotifications`. I'm happy to fix that if you'd like.

**Comment by mcguirepr89** [comment]
Thanks, @joeweiss I appreciate that and would love to accept your offer to correct the relative import stuff if you would be so kind :)

**Comment by joeweiss** [comment]
@mcguirepr89 Looks like you went ahead and fixed them. I'll discard my PR.

**Pull request merged**
