### PR TITLE
Update advanced.php

### PR DESCRIPTION
**Pull request by ehpersonal38**
Fixes issue #145

### CODE REVIEW

**Comment by mcguirepr89** [comment]
Whoohoo!!!! @DD4WH Frank will be pleased!

**Comment by mcguirepr89** [comment]
I've given this a test, and while it does allow me to update both in tandem, it seems that it also allows the Extraction Length value to be greater than the Recording Length value, which should not be allowed

**Comment by ehpersonal38** [comment]
Oops! Completely forgot to change the tag name to the right one. Try now?

**Review by mcguirepr89 — APPROVED** [review]
S'perfect now!

**Pull request merged**
