### PR TITLE
WIP: Heartbeat

### PR DESCRIPTION
**Pull request by phillprice**
Should someone want to prove the analysis service hasn't fallen over silently, this allows the service to send a heartbeat by CURLing a URL such as in uptime-kuma

### CODE REVIEW

**Comment by ehpersonal38** [comment]
Looks good to me, thanks @phillprice for the PR! 🙂

**Comment by mcguirepr89** [comment]
I'm sorry to poke in here -- would one of you mind explaining a bit further how the heartbeat works and how it might be used? Specifically what curling a URL would say about the `birdnet_analysis.service`? Is the response parsed somewhere? From what I can tell, this would simply plop some curl output into the log? What am I missing? SORRY!

**Comment by ehpersonal38** [comment]
In the OP he gives the example of [uptime-kuma ](https://github.com/louislam/uptime-kuma )being used alongside this heartbeat. So presumably he can check his uptime-kuma dashboard to see if his BirdNET analysis stopped sending updates (i,e, it's hung), and then manually restart the service. Agreed on the ICMP!

**Comment by phillprice** [comment]
Admittedly I put this PR in WIP for Work In Progress. 

Uptime Kuma works for **passive** remote monitoring (i.e. BirdNET-Pi pings Uptime Kuma, rather then Uptime Kuma pings BirdNET-Pi ) using a URL like this...
`http://uptime-kuma-url.tld/api/push/bXotRXdUMS?status=up&msg=OK&ping=`

I think it could be lighter by possibly changing the request to a HEAD request from GET, and not publishing the response in the log.

**Comment by phillprice** [comment]
with `-I` (for HEAD requests) and prefixing time before curl:

```

Oct  9 11:34:32 birdpi birdnet_analysis.sh[2025377]: real#0110m0.042s
Oct  9 11:34:32 birdpi birdnet_analysis.sh[2025377]: user#0110m0.012s
Oct  9 11:34:32 birdpi birdnet_analysis.sh[2025377]: sys#0110m0.007s
```
without `-I` i.e. a GET request:

```
Oct  9 11:36:03 birdpi birdnet_analysis.sh[2026899]: real#0110m0.048s
Oct  9 11:36:03 birdpi birdnet_analysis.sh[2026899]: user#0110m0.012s
Oct  9 11:36:03 birdpi birdnet_analysis.sh[2026899]: sys#0110m0.007s
```

Hmm thats' hardly conclusive to any benefit which is unexpected

**Pull request merged**
