### PR TITLE
Adding Flake8 Github Action for Python Linting 

### PR DESCRIPTION
**Pull request by jmherbst**
Hello,

I noticed the discussion (https://github.com/mcguirepr89/BirdNET-Pi/commit/a6a8c3b46f5d1f65b465aaa0d2b8359021e9be55#commitcomment-73344158 ) about python indentation causing errors and thought I'd get your thoughts on adding a python linter as a github action for pull requests.

This is a working action and I went ahead and corrected the styling/linting on `script/analyze.py`.

I could take a stab at correcting the style/lint of the remaining python files if you like this idea and would like to review those changes? 

You can see the GH Action in... _action_ (😎 ) over on https://github.com/jmherbst/BirdNET-Pi/pull/1, and you can see it catching an error on https://github.com/jmherbst/BirdNET-Pi/pull/2

### CODE REVIEW

**Comment by mcguirepr89** [comment]
Hi, @jmherbst --
This looks like a pretty helpful addition!
One question/suggestion:
It looks like line 15 of `.github/workflows/ci.yml` uses python 3.7.* to test, though Debian Bullseye ships with 3.9.* by default. Would it be easy enough to change that to 3.9.*? I suppose for linting it won't matter _too_ much.

**Comment by mcguirepr89** [comment]
@jmherbst Thank you so much -- this is great. I would love to take you up on the offer to run through the remaining python scripts for style/linting. I'll hold off on this PR to look through them all together :pray: prayer hands!

**Comment by ehpersonal38** [comment]
This is pretty cool! Glad to see how a little mistake can contribute to the greater good 😄

**Comment by jmherbst** [comment]
I was working with an out-of-date `main`.  I've got the style+lint fix commits pushed, but let me get main merged in and conflicts resolved now.

**Comment by mcguirepr89** [comment]
Sounds good!! `privacy_server.py` can get chucked as it is no longer part of the repo

Thanks for your help :)

**Comment by jmherbst** [comment]
Here's the CI run over on my fork - https://github.com/jmherbst/BirdNET-Pi/runs/6388313650?check_suite_focus=true

Not sure if you have to enable Github Action runs over here for it to run on [264380a](https://github.com/mcguirepr89/BirdNET-Pi/pull/267/commits/264380a37f76064c10ba8c633c70502bc9b2b570) ?

**Comment by mcguirepr89** [comment]
I'll have to figure how to enable/configure the actions to run for this repo, but I'm sure I'll figure it out

**Pull request merged**
