### PR TITLE
Reduce code duplication and cpu usage of birdnet_analysis.sh

### PR DESCRIPTION
**Pull request by Nachtzuster**
There's two parts to this PR:
- consolidate duplicate code.
- optimize by trying to avoid ffmpeg (ffmpeg startup on a non-existing wav file is about 0.75s)

rationale: systemd reports 4.75s cpu time for birdnet_analysis.sh, while analyze time reported by server.py is 3.1s for 15s wav files.
the changes take the 4.75s down to about 1s

Should help lower end devices and improves battery life in a field deployment.

Tested with Debian Bullseye on a Libre Potato (which performance wise sits between a RPi3 and RPi4)

### CODE REVIEW

**Comment by mcguirepr89** [comment]
Exciting!!! Testing now~~

**Comment by mcguirepr89** [comment]
A great improvement! Works like a charm!!

RaspiOS-Lite, however, doesn't come with `lsof` out of the box, so in addition to the changes to `birdnet_analysis.sh`, we'll want to add that to the `install_services.sh`'s `install_depends()` function and this makes me want to try out a new updating method I've been thinking about.

Since the update script mostly just uses `git pull` to get new things, I add in little snippets here and there to address changes outside of `git`. This sometimes means folks need to run the update script twice: first to `git pull` the new `update_birdnet.sh` and then a second time to execute whatever is new in the script.

The new idea is actually an older one I tried but abandoned wherein `update_birdnet.sh` also calls another script. This second script, `update_birdnet_extras.sh` or whatever, would be where little snippets like:
```
if ! which lsof &>/dev/null;then
  sudo apt install update && sudo apt -y install lsof
fi
```

I'll make some changes to this PR and will merge it with those changes -- 

THANK YOU!!!!!!!!!!!!!!!!

**Comment by mcguirepr89** [comment]
I suppose that snippet can also just go right into `birdnet_analysis.sh` --

What are your thoughts?

**Comment by Nachtzuster** [comment]
@mcguirepr89 I know my feedback is not too relevant anymore, but looks like things ended up in the right place. :-) -thanks!
(I'm in Europe and the daytime job has priority, so my timing _will_ be off)

**Comment by mcguirepr89** [comment]
@Nachtzuster sorry for moving quickly! Another cool idea was in the works and so things just sort of fell into place for us to move forward with the new `update_birdnet_snippets.sh` that is called in `update_birdnet.sh` now.
Thank you again for the elegant edits!

**Pull request merged**
