### PR TITLE
Minor changes

### PR DESCRIPTION
**Pull request by ehpersonal38**

### CODE REVIEW

**Review by mcguirepr89 — APPROVED** [review]
I like this  little jump -- very helpful.

PS
I noticed that the copy links are wonky on mobile views --- let's take another look at that

**Comment by ehpersonal38** [comment]
> I like this little jump -- very helpful.
> 
> PS I noticed that the copy links are wonky on mobile views --- let's take another look at that

Thank you!

Sure, what about them is wonky? And what browser?

**Comment by mcguirepr89** [comment]
This is my mobile view on Chrome and Safari:
IMG_0917
IMG_0918

You'll see the copy link floats up in the top right of the viewport -- the same can be seen on the other pages, I just don't have a screenshot for those.

I haven't looked into fixing this yet myself (I'm adding an automatic HotSpot to a pre-installed image today that will allow users to just download the pre-installed image, connect to the HotSpot and then either choose the WiFi they want to connect to, or just view things locally (so that BirdNET-Pi can live on the side of a mountain and be visited periodically to connect to it's hotspot to view/copy data without a network).

**Comment by ehpersonal38** [comment]
Thanks for bringing this to my attention! I only have an Android device and this issue wasn't occuring, it seems to be a thing with iOS devices only. I just created a pull request, it seemed to fix it on an iOS emulator I ran, but I would appreciate you verifying if the issue is fixed or not.

The hotspot idea sounds very cool! The Pi would be then acting as its own router of sorts? Definitely will be useful for people 'in the field.'

**Comment by mcguirepr89** [comment]
>The Pi would be then acting as its own router of sorts? Definitely will be useful for people 'in the field.'

Yep! If I make it do everything I hope it will, it should be ideal for the 'field researcher' but should also be super duper handy for any user.
For the field researcher, the tool would be used like this:
- Insert the SD card that has the BirdNETPi.img
- It will present the BirdNET-Pi HotSpot
- Connect to it from any device and configure the settings for the installation
- Come back when you want the data
(Notice this is a _fully_ offline set of events)

For the average user (me), the tool would be used like this:
- Insert the SD card that has the BirdNET-Pi.img
- It will present the BirdNET-Pi HotSpot
- Connect to it from any device and choose from the available WiFi networks the one BirdNET-Pi should use
- Never think about it again, unless you change your router settings, at which point the HotSpot will come back up and you can enter in the new WiFi credentials. Likewise you can take your installation with you when you travel as the HotSpot will be available anytime it cannot connect to a known WiFi network
(Notice this set of events adapts to the network environment)

I implemented this in the last pre-installed image (version 0.10), but SOOO much has changed, including how this automatic hotspot is handled :)

I'm excited!

**Pull request merged**
