### PR TITLE
Configurable service logging options for select services

### PR DESCRIPTION
**Pull request by jaredb7**
After some services were recently quieted down by adjusting the log level for e.g ffmpeg. I realised that the troubleshooting in Discussion #842 would not be as easy once that service had been quietened down, requiring the user edit the script for the service to get more output again.

It would be nice if the user can easily adjust the log level again so that that they can investigate or debug a issue since output is not generated by default any more, So now the Livestream, Spectrogream and Birdnet Recording have a adjustable log levels to help with this when needed.
The relevant service is restarted once the log level has been changed.

This idea would be expanded into other areas if need but everything seems fine at the moment :)

image

### CODE REVIEW

**Comment by lloydbayley** [comment]
I like the idea and am testing it, however, for some reason, it's not creating the entries in the birdnet.conf when I save. Will investigate more.

**Comment by lloydbayley** [comment]
Ok. It's the initial save that isn't creating the variables. update_birdnet_snippets.sh creates them but the initial save doesn't. Will leave it with you.

**Comment by jaredb7** [comment]
Yeah the update_birdnet_snippets.sh script inserts initial value for the settings that caught me out the first time where I had not run it yet.

 I was following how the existing settings worked and they all rely (assuming the setting isn't already in the config file) on the update_birdnet_snippets script to create them and the settings pages just update the values but never inserts them if they don't exist.
 
 I'll pop in a quick check insert the setting if it didn't exist as a fallback so it'll work regardless.

**Comment by lloydbayley** [comment]
Yep. Good one. Aside from that, it should be good to go once you fix that. I'll check it again then it can go in. I can't do that, I'm afraid, that's up to ~~the lord of the birds~~ @ehpersonal38. :smile:

**Comment by lloydbayley** [comment]
That's really scary @jaredb7 I was just looking at this and wondering how you were getting on! Next minute I see the notification. I'll give it a test now!

**Comment by lloydbayley** [comment]
Nice one! Looking & working good/well.
One small problem seems to be a version-control conflict in scripts/install_language_label_nm.sh
Perhaps it was updated in the meantime..I have absolutely no idea how to fix that.
Over to you @ehpersonal38 ! (He's going to hate me for that).... :smile:

**Comment by jaredb7** [comment]
Oh whoops!, yeah those two scripts were updated in between my changes. I resolved the conflict with birdnet_recording.sh and update_birdnet_snippets.sh but didn't see the language_label_nm.sh one unless that's something just showing on your end :(

**Comment by ehpersonal38** [comment]
Looks good! There was just a slight bug - you removed a `fi` when resolving the conflicts in update_birdnet_snippets.sh. All's well now though. Thanks for the PR. 😄

**Comment by lloydbayley** [comment]
Ahh crap....I missed that. Just tested the bit he fixed. Grasshopper has a lot to learn master.
Bugger.

**Comment by jaredb7** [comment]
> Looks good! There was just a slight bug - you removed a `fi` when resolving the conflicts in update_birdnet_snippets.sh. All's well now though. Thanks for the PR. 😄

I'm guilty! I removed it thinking..... oh we don't need that it's just getting in the way of my changes :P

**Pull request merged**
