### PR TITLE
Bash Scripts - Create a file path and directory resolver & migrate away from hard coded paths

### PR DESCRIPTION
**Pull request by jaredb7**
Thorough review of what I've done and additional testing needed since this can break systems.

Same implementation as with the Python scripts (#930 & #925) - Created a file path and directory resolver that can be called with a file name or directory and returns a path relative to a home path (which is still currently fixed to user id 1000 but the intention is that it can be easily changed)

Updated all scripts that had hard coded paths to use the new resolver EXCEPT the install scripts. There were no logic changes with any of the scripts, just path replacements.

I've tested nearly all scripts the best I can and also tested the destructive scripts such as clean_all_data.sh, uninstall.sh, created_db.sh which all function correctly

I haven't tested the following (e.g don't use Apprise) but on principle they should still work:
```
weekly_report.sh
custom_recording.sh
```
And this script seems unused:
`write_config.sh`

Included test_filepath_resolver_common.sh which runs a simple list of tests against the new get_file_path and get_directory to ensure they return what we expect. This proves useful as sometimes getting the correct output with string manipulation was sometimes be tricky
The script should be run first to validate everything is ok, it should return nothing if all was ok
./tests/test_filepath_resolver_common.sh

Relies upon #925 for /config/filepath_map.json and the installation of jq (a command line parser for JSON files https://stedolan.github.io/jq/)

### CODE REVIEW

**Comment by ehpersonal38** [comment]
I did some quick testing and I'm experiencing quite a lot of problems. When I run `./tests/test_filepath_resolver_common.sh` it seems to get into an infinite loop and never stops (I put `set -x` at the top of the script). Also, the core services are broken and the analysis isn't working anymore. Running `birdnet_analysis.sh` manually produced the same infinite loop issue. Let me know if you need any more info.

**Comment by jaredb7** [comment]
Hmm I think may know what's going on in the `birdnet_analysis.sh` (and practically all scripts really), might have to change the order of the code in update_snippets

Just to verify, do you recall the output blitzing past your screen and looking somewhat like this?
image
image

if the test case is printing something like this - then it's likely ok. if you have -x on it will sort of look like a loop as it tests everything 3 times (once for /home/pi, again for /home/another_usr and then /opt/BirdNET-pi) and just checks the structure is correct with those as the "home" folder.
image

**Comment by jaredb7** [comment]
I reproduced the issue and fixed the issue with #935 

If you're still on the PR-Dev branch you'll have to get git to pull in the changes as  update_birdnet.sh will be broken due to common.sh script requiring the /config/ which doesn't exist at /usr/local/bin at the moment

```
git reset --hard HEAD
git fetch
git pull
```

then `update_birdnet_snippets.sh` to have the symbolic links fixed (these get created first)

At this point update_birdnet_snippets shouldn't produce any errors, just complete and then restart the core services.
Then everything should be back to normal.... hopefully

**Comment by ehpersonal38** [comment]
Unfortunately still getting an infinite loop with both the test file and running birdnet_analysis.sh. I let the test run for about 10 sec, here's the `set -x` output - 
[file.txt](https://github.com/mcguirepr89/BirdNET-Pi/files/11587074/file.txt)

**Comment by jaredb7** [comment]
That output suggests the test is passing (reads the JSON file and then slices through it to get the bits required for the particular path or directory.
Why this passes ok is because the test pulls in files relative to it's location so ../scripts/common.sh and common.sh pulls the JSON file from one folder above ../config/jsonfile.json
But the services and other are running from another path where /config isn't accessible

This PR has the fix to the /usr/local/bin sym links and improvement to the test so we know what its up to, it does actually take a little while to complete the entire run too
https://github.com/mcguirepr89/BirdNET-Pi/pull/935

This is what it'll output now
```
Testing symbolic links required by services exists...
Symbolic link check completed successfully.
Testing of '/home/pi' as home directory, starting....
Testing of '/home/pi' as home directory, completed successfully.
Testing of '/home/another_user' as home directory, starting....
Testing of '/home/another_user' as home directory, completed successfully.
Testing of '/opt/birdnet' as home directory, starting....
Testing of '/opt/birdnet' as home directory, completed successfully.
```

And a example if things aren't right
```
Testing symbolic links required by services exists...
WARNING!! required symbolic link --> /usr/local/bin/config does not exist; create it with 'sudo ln -sf /home/pi/BirdNET-Pi/config /usr/local/bin/'
Symbolic link check failed, see errors above.
```

**Pull request merged**
