### PR TITLE
Update style.css

### PR DESCRIPTION
**Pull request by ehpersonal38**
Weird position: absolute behavior on iOS devices, hoping this fixes it

### CODE REVIEW

**Comment by mcguirepr89** [comment]
Unfortunately, it doesn't fix things :/

It's not the worst thing -- I may just make it "hidden" for small screens -- I will check my partner's MacBook to see if the desktop Safari has any trouble (I doubt it have trouble) and then will figure something out. I definitely want to keep it anywhere it works

**Comment by ehpersonal38** [comment]
> Unfortunately, it doesn't fix things :/
> 
> It's not the worst thing -- I may just make it "hidden" for small screens -- I will check my partner's MacBook to see if the desktop Safari has any trouble (I doubt it have trouble) and then will figure something out. I definitely want to keep it anywhere it works

Darn! I was really confident in that working. Could you try one last thing? Replace the entire "a" tag on line 100 of overview.php with this:
```php
<a style="float:right;width:25px;height:25px" target="_blank" href="index.php?filename=<?php echo $mostrecent['File_Name']; ?>"><img class="" width="25" height="25" src="images/copy.png"></a>
```

It's a little uglier but let me know if it works at all.

**Comment by mcguirepr89** [comment]
False alarm! I forgot to clear my cache! It DOES work! (I didn't need to use the part you just sent above, BUT thank you!)

**Review by mcguirepr89 — APPROVED** [review]
Wonderful!!

**Comment by ehpersonal38** [comment]
Darn!


> False alarm! I forgot to clear my cache! It DOES work! (I didn't need to use the part you just sent above, BUT thank you!)

Ah, the infamous caching! Glad to hear everything works!

**Pull request merged**
