### PR TITLE
Adding custom host names

### PR DESCRIPTION
**Pull request by davidmam**
This adds the variable BIRDNET_HOST in the config file (default to birdnetpi so backward compatible). It uses the value of this variable when setting the .local URLs, hostname etc. 

This allows multiple birdnetpi to appear on the same network, each with a unique hostname.

### CODE REVIEW

**Comment by davidmam** [comment]
Closed as there is still work to do on this.

**Comment by mcguirepr89** [comment]
Hi, Dr. Martin -- this feature is now a apart of the `forms` branch -- you can preset the hostname using the Raspberry Pi Imager SD card imaging tool and the installation will change the installation to use the hostname.

So now, if you set the hostname before (or after) burning the SD card, the installation will be reachable at "mynewhostname.local"

Likewise, if you change the device's hostname after installation and then run an update, the installation will use that new hostname for all of its web interface URLs. With all of that said, setting the "BIRDNETPI_URL" in `birdnetpi.conf` will override this feature and will set the URLS to those set in the Custom URLs section.

**Comment by davidmam** [comment]
Ah, I wasn't aware of that. I had just been following the standard headless install.  No problem

How do you specifically access the forms branch?

I'm currently trying to set one up with solar power on a cellular modem.

..d

Dr David Martin
Senior Lecturer in Bioinformatics
College of Life Sciences
University of Dundee


________________________________

**Comment by mcguirepr89** [comment]
>How do you specifically access the forms branch?

To utilize the `forms` branch (or to ensure that your installation uses it for installation), the following is the installation one-liner:
```
curl -s https://raw.githubusercontent.com/mcguirepr89/BirdNET-Pi/forms/newinstaller.sh | bash
```
Notice the `forms` slug in the curl URL -- that ought to do the trick for you.

My best regards!!
Patrick McGuire

**Pull request closed without merging**
