### PR TITLE
Update overview.php

### PR DESCRIPTION
**Pull request by ehpersonal38**
Now the left tally chart updates with JS too!

Also cleaned up & optimized a few lines of code.

### CODE REVIEW

**Review by mcguirepr89 — APPROVED** [review]
:1st_place_medal: :100:

**Comment by mcguirepr89** [comment]
@ehpersonal38 I have been meaning to ask if you wouldn't mind sharing where your BirdNET-Pi will be listening? (if you care to share)

**Comment by ehpersonal38** [comment]
> @ehpersonal38 I have been meaning to ask if you wouldn't mind sharing where your BirdNET-Pi will be listening? (if you care to share)

Sure, I'm currently in Florida!

**Comment by mcguirepr89** [comment]
I hope you'll consider POSTing to BirdWeather (check out Privacy Mode in "Tools" > "Settings" > "Advanced Settings" and `scripts/privacy_server.py` before you commit if you're worried about sharing selections that might include humans by accident)

**Comment by ehpersonal38** [comment]
> I hope you'll consider POSTing to BirdWeather (check out Privacy Mode in "Tools" > "Settings" > "Advanced Settings" and scripts/privacy_server.py before you commit if you're worried about sharing selections that might include humans by accident)

Thank you for the suggestion! I think privacy mode is a great feature that really lowers the barrier of entry into making your data public. I'll definitely consider it in the future but for now I prefer to keep things local.

Also, do you have any ideas you need help implementing? I'm quite familiar with web development and not as much with bash/system stuff, but I can at least try to help with anything. Let me know!

**Pull request merged**
