### PR TITLE
Fixing style.css again

### PR DESCRIPTION
**Pull request by ehpersonal38**
Hopefully this fixes things for good, had to move class="relative" to the td instead of the tr...

### CODE REVIEW

**Review by mcguirepr89 — COMMENTED** [review]
I think these changes are good, but it is hard to tell!!
The repo has been seeing a HUGE spike in traffic, and as a result the database got locked up!!!! (I suppose from visitors hitting the page so often -- like over 2,000 views today . . . nuts!!! Did you see the Star Gazer count went from 57 to over 130???) I will pull it when I can test it more!

**Comment by ehpersonal38** [comment]
> I think these changes are good, but it is hard to tell!! The repo has been seeing a HUGE spike in traffic, and as a result the database got locked up!!!! (I suppose from visitors hitting the page so often -- like over 2,000 views today . . . nuts!!! Did you see the Star Gazer count went from 57 to over 130???) I will pull it when I can test it more!

Well if you don't notice anything different then that's good! Hopefully that means it's all working.

WOW!! Do you have any idea where all the views and stars came from? Like the referring url? That's great though! The more people discovering the project the better.

**Comment by RHeynsZa** [comment]
I saw this on the HomeAssistant subreddit, which could have an influx

**Comment by ehpersonal38** [comment]
> I saw this on the HomeAssistant subreddit, which could have an influx

Awesome! It's cool to see how other people are finding out about the project.

@mcguirepr89 Apparently these two threads popped up yesterday which probably account for the influx of traffic:
https://news.ycombinator.com/item?id=31072485
https://www.reddit.com/r/homeassistant/comments/u6nacb/birdnetpi_automated_locally_run_bird_sound/

**Comment by mcguirepr89** [comment]
There were no indications in the GitHub "Pulse" yesterday as to where the clicks were coming from, but they're visible today, and apparently most of the traffic is coming from this: https://news.ycombinator.com/item?id=31072485

**Pull request merged**
