### PR TITLE
Overview Updates

### PR DESCRIPTION
**Pull request by fordb**

### CODE REVIEW

**Comment by jmtmp** [comment]
Hi, I'm completely new to python, but still I tried to prepare a new overview chart and it works.
Sorry but I don't know how to upload my new python file.
Combo-2024-04-16

**Comment by jmtmp** [comment]
some more coding....
1) adjusted hourly chart (to all birds detected during the day)
2) bottom daily chart converted to semi-monthly overview
3) code optimalization
Combo-2024-04-18
Combo2-2024-04-18

**Comment by jmtmp** [comment]
How about canceling the side information panel on the overview
info

**Comment by alexbelgium** [comment]
Hi your work looks very nice this repo is inactive but there is an active fork here that might be interested! https://github.com/Nachtzuster/BirdNET-Pi

**Comment by jmtmp** [comment]
Hi, I'm still using the original version, I don't want to migrate yet,
maybe later.
If you want to play with my graphs or share them in a new fork, I am
attaching them.
Good luck
Martin

st 29. 5. 2024 v 23:03 odesílatel Alexandre ***@***.***>
napsal:

**Comment by alexbelgium** [comment]
Thanks! I'll look at it they look great :) BTW I noted that kahst said in a recent discussion that he has applied for funding to develop birdnet-pi (https://github.com/Nachtzuster/BirdNET-Pi/discussions/75#discussioncomment-9601596) so we'll see how that develops too

**Pull request closed without merging**
